// CheatMe.c
// Generated by decompiling CheatMe.exe
// using Reko decompiler version 0.9.0.0.

#include "CheatMe.h"

// 00401000: Register ptr32 fn00401000()
ptr32 fn00401000()
{
	return 0x004033A0;
}

// 00401010: void fn00401010(Stack word32 dwArg04)
void fn00401010(word32 dwArg04)
{
	ptr32 * esp_14;
	word32 eax_16;
	_acrt_iob_func();
	*esp_14 = fp + 0x08;
	*(esp_14 - 0x04) = 0x00;
	*(esp_14 - 0x08) = dwArg04;
	*(esp_14 - 0x0C) = eax_16;
	struct Eq_31 * eax_30 = fn00401000();
	*(esp_14 - 0x0010) = eax_30->dw0004;
	*(esp_14 - 0x0014) = eax_30->dw0000;
	_stdio_common_vfprintf();
}

// 00401040: Register word32 fn00401040(Register out (ptr32 Eq_54) edxOut, Register out Eq_55 blOut)
word32 fn00401040(struct Eq_54 & edxOut, union Eq_55 & blOut)
{
	while (true)
	{
		Sleep(1000);
		system("cls");
		struct Eq_54 * edx_100 = globals->ptr403398;
		Eq_68 ebx_142 = globals->t403018;
		struct Eq_54 * edi_118 = globals->ptr403394;
		if (edx_100 == (struct Eq_54 *) ~0x00)
		{
			if (edi_118 <= null && ebx_142 <= 0x00)
				edx_100 = null;
			else
			{
				globals->ptr403394 = edi_118 - 0x01;
				--edi_118;
				edx_100 = (struct Eq_54 *) 0x3B;
			}
			globals->ptr403398 = edx_100;
		}
		if (edi_118 == (struct Eq_54 *) ~0x00)
		{
			if (ebx_142 > 0x00)
			{
				globals->t403018 = ebx_142 - 0x01;
				--ebx_142;
				edi_118 = (struct Eq_54 *) 0x3B;
			}
			else
				edi_118 = null;
			globals->ptr403394 = edi_118;
		}
		if (ebx_142 == 0x00 && (edi_118 == null && edx_100 == null))
			break;
		SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
		fn00401010(4202772);
		SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
		fn00401010(4202804);
		SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
		fn00401010(0x00402174);
		fn00401010(4202884);
		SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
		fn00401010(4202920);
		fn00401010(0x004021C4);
		fn00401010(4202920);
		--globals->ptr403398;
	}
	byte * ecx_73 = &globals->b40301C;
	do
	{
		ecx_73 = ecx_459 + 0x01;
		ecx_459 = ecx_73;
	} while (*ecx_459 != 0x00);
	struct Eq_54 * ecx_132 = ecx_73 - &globals->b40301D;
	if (ecx_73 > &globals->b40301D)
	{
		do
		{
			if (edi_118 < ecx_132)
			{
				do
				{
					if (edx_100 < ecx_132)
					{
						do
						{
							edx_100[4206620] = (struct Eq_54) ((byte) edx_100[4206620] + 0x06);
							byte * eax_103 = &globals->b40301C;
							++edx_100;
							do
							{
								eax_103 = eax_460 + 0x01;
								eax_460 = eax_103;
							} while (*eax_460 != 0x00);
						} while (edx_100 < eax_103 - 0x0040301D);
						globals->ptr403398 = edx_100;
					}
					byte * ecx_116 = &globals->b40301C;
					++edi_118;
					do
					{
						ecx_116 = ecx_461 + 0x01;
						ecx_461 = ecx_116;
					} while (*ecx_461 != 0x00);
					ecx_132 = ecx_116 - 0x0040301D;
				} while (edi_118 < ecx_116 - 0x0040301D);
				globals->ptr403394 = edi_118;
			}
			byte * ecx_137 = &globals->b40301C;
			ebx_142 = (word32) ebx_142.u0 + 0x01;
			do
			{
				ecx_137 = ecx_462 + 0x01;
				ecx_462 = ecx_137;
			} while (*ecx_462 != 0x00);
			ecx_132 = ecx_137 - 0x0040301D;
		} while (ebx_142 < ecx_137 - 0x0040301D);
		globals->t403018 = ebx_142;
	}
	SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
	fn00401010(4202772);
	SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
	fn00401010(4202804);
	SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
	fn00401010(0x004021E4);
	SetConsoleTextAttribute(GetStdHandle(~0x0A), (WORD) ~0x0A);
	fn00401010(0x004021F4);
	Sleep(3240000);
	edxOut = edx_100;
	blOut.u0 = <invalid>;
	return 0x00;
}

// 004014C5: Register Eq_93 Win32CrtStartup()
Eq_93 Win32CrtStartup()
{
	word24 ebx_24_8_85 = SLICE(ebx, word24, 8);
	fn0040188E();
	Eq_55 esp_266;
	struct Eq_300 * ebp_141 = fn00401B80(ebx, esi, edi, dwLoc0C, 0x14);
	word32 dwLoc0C_336 = 0x01;
	ptr32 esp_113 = fp - 0x08;
	if ((byte) (uint32) (uint8) fn00401666(edx, ebx, 0x01) != 0x00)
	{
		*(ebp_141 - 0x19) = 0x00;
		*(ebp_141 - 0x04) &= 0x00;
		word32 edx_108;
		*(ebp_141 - 0x24) = (byte) (uint32) (uint8) fn00401634(out edx_108);
		uip32 eax_55 = globals->dw403354;
		word32 ebx_137 = SEQ(ebx_24_8_85, 0x00);
		if (eax_55 != 0x01)
		{
			Eq_93 eax_313;
			if (eax_55 == 0x00)
			{
				globals->dw403354 = 0x01;
				struct Eq_393 * esp_87;
				word32 eax_89;
				word32 edx_91;
				initterm_e();
				dwLoc0C_336 = 0x004020F0;
				if (eax_89 != 0x00)
				{
					*(ebp_141 - 0x04) = ~0x01;
					eax_313.u0 = 0xFF;
					goto l0040149F;
				}
				esp_87->dw0004 = 0x004020E0;
				esp_87->dw0000 = 0x004020D8;
				word32 esp_104;
				initterm();
				globals->dw403354 = 0x02;
				esp_113 = esp_104 + 0x08;
			}
			else
			{
				*(ebp_141 - 0x19) = 0x01;
				ebx_137 = SEQ(ebx_24_8_85, 0x01);
			}
			union Eq_93 * esp_119 = esp_113 - 0x04;
			*esp_119 = *(ebp_141 - 0x24);
			fn004017BA(*esp_119);
			ptr32 esp_128 = (char *) esp_119 + 0x04;
			Eq_93 eax_129 = fn00401946();
			word32 edi_131 = 0x00;
			if (*eax_129 != 0x00)
			{
				*esp_119 = (union Eq_93 *) eax_129;
				Eq_55 esp_146 = <invalid>;
				esp_128 = (word32) esp_146 + 0x04;
				<anonymous> ** esi_145;
				if ((byte) (uint32) (uint8) fn00401726(ebx_137, eax_129, 0x00, out edx_108, out ebx_137, out ebp_141, out esi_145, out edi_131) != 0x00)
				{
					<anonymous> * esi_158 = *esi_145;
					*esp_146 = edi_131;
					*(esp_146 - 0x04) = 0x02;
					*(esp_146 - 0x08) = edi_131;
					fn00401916();
					esi_158();
				}
			}
			Eq_93 eax_173 = fn0040194C();
			if (*eax_173 != edi_131)
			{
				*(esp_128 - 0x04) = (union Eq_93 *) eax_173;
				Eq_55 esp_190 = <invalid>;
				word32 * esi_189;
				word32 ebx_365;
				word32 edi_366;
				if ((byte) (uint32) (uint8) fn00401726(ebx_137, eax_173, edi_131, out edx_108, out ebx_365, out ebp_141, out esi_189, out edi_366) != 0x00)
				{
					*esp_190 = *esi_189;
					register_thread_local_exe_atexit_callback();
				}
			}
			word32 eax_225;
			word32 edx_227;
			get_initial_narrow_environment();
			word32 * eax_232;
			word32 edx_234;
			_p___argv();
			ptr32 esp_238;
			word32 * eax_240;
			_p___argc();
			word32 esi_237 = *eax_232;
			*(esp_238 - 0x04) = eax_225;
			*(esp_238 - 0x08) = esi_237;
			*(esp_238 - 0x0C) = *eax_240;
			Eq_55 ebx_252 = <invalid>;
			word32 edx_255;
			byte bl_364;
			Eq_93 eax_251 = fn00401040(out edx_255, out bl_364);
			byte bl_281 = (byte) ebx_252;
			esi = eax_251;
			esp_266.u0 = <invalid>;
			if ((byte) (uint32) (uint8) fn00401A71() != 0x00)
			{
				if (bl_281 == 0x00)
					cexit();
				union Eq_622 * esp_294 = esp_266 - 0x04;
				*esp_294 = 0x00;
				*(esp_294 - 0x04) = 0x01;
				fn004017D7(*esp_294);
				*(ebp_141 - 0x04) = ~0x01;
				eax_313 = eax_251;
l0040149F:
				fs->dw0000 = *(ebp_141 - 0x10);
				return eax_313;
			}
l004014B6:
			union Eq_93 * esp_277 = esp_266 - 0x04;
			*esp_277 = (union Eq_93 *) esi;
			exit(*esp_277);
		}
	}
	fn00401952(0x07);
	esp_266 = fp - 0x0C;
	goto l004014B6;
}

// 004015F0: Register (ptr32 Eq_647) fn004015F0(Stack (ptr32 Eq_648) dwArg04, Stack uint32 dwArg08, Register out (ptr32 Eq_647) edxOut)
struct Eq_647 * fn004015F0(struct Eq_648 * dwArg04, uint32 dwArg08, struct Eq_647 & edxOut)
{
	struct Eq_647 * eax_32;
	struct Eq_652 * ecx_13 = dwArg04 + dwArg04->dw003C / 0x0040;
	struct Eq_647 * edx_16 = &ecx_13->w0014 + 0x02 + (word32) ecx_13->w0014 / 22;
	struct Eq_647 * esi_19 = edx_16 + (word32) ecx_13->w0006;
	for (; edx_16 != esi_19; ++edx_16)
	{
		if (dwArg08 >= edx_16->dw000C && dwArg08 < edx_16->dw0008 + edx_16->dw000C)
		{
			eax_32 = edx_16;
			goto l0040162D;
		}
	}
	eax_32 = null;
l0040162D:
	edxOut = edx_16;
	return eax_32;
}

// 00401634: Register byte fn00401634(Register out ptr32 edxOut)
byte fn00401634(ptr32 & edxOut)
{
	word32 eax_7 = fn00401DDA();
	if (eax_7 == 0x00)
	{
l0040165E:
		edxOut = edx;
		return 0x00;
	}
	else
	{
		edx = fs->ptr0018->ptr0004;
		do
		{
			__lock();
			ptr32 eax_24;
			__cmpxchg(globals->dw403358, edx, 0x00, out eax_24);
			if (eax_24 == 0x00)
				goto l0040165E;
		} while (edx != eax_24);
		edxOut = edx;
		return 0x01;
	}
}

// 00401666: Register byte fn00401666(Register word32 edx, Register word32 ebx, Stack word32 dwArg04)
byte fn00401666(word32 edx, word32 ebx, word32 dwArg04)
{
	if (dwArg04 == 0x00)
		globals->b40335C = 0x01;
	fn00401C0A(edx, ebx);
	if (fn004018F2() == 0x00)
		return 0x00;
	if (fn004018F2() != 0x00)
		return 0x01;
	fn004018F2();
	return 0x00;
}

// 00401726: Register byte fn00401726(Register word32 ebx, Register Eq_93 esi, Register word32 edi, Register out ptr32 edxOut, Register out ptr32 ebxOut, Register out ptr32 ebpOut, Register out ptr32 esiOut, Register out ptr32 ediOut)
byte fn00401726(word32 ebx, Eq_93 esi, word32 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 eax_100;
	struct Eq_300 * ebp_13 = fn00401B80(ebx, esi, edi, dwLoc0C, 0x08);
	*(ebp_13 - 0x04) &= 0x00;
	word24 eax_24_8_101 = 0x5A;
	if (globals->w400000 == 23117)
	{
		struct Eq_781 * eax_25 = globals->ptr40003C;
		eax_24_8_101 = SLICE(eax_25, word24, 8);
		eax_24_8_101 = SLICE(eax_25, word24, 8);
		if (eax_25->dw400000 == 0x4550 && eax_25->w400018 == 0x010B)
		{
			struct Eq_796 * eax_40 = fn004015F0(&globals->w400000, ebp_13->dw0008 - 0x00400000, out edx);
			eax_24_8_101 = SLICE(eax_40, word24, 8);
			eax_24_8_101 = SLICE(eax_40, word24, 8);
			if (eax_40 != null && eax_40->dw0024 >= 0x00)
			{
				*(ebp_13 - 0x04) = ~0x01;
				eax_100 = SEQ(eax_24_8_101, 0x01);
l004017AA:
				fs->dw0000 = *(ebp_13 - 0x10);
				ptr32 ebp_79 = ebp_13->ptr0000;
				edxOut = edx;
				ebxOut = dwArg04;
				ebpOut = ebp_79;
				esiOut = dwArg00;
				ediOut = 0x08;
				return (byte) eax_100;
			}
		}
	}
	*(ebp_13 - 0x04) = ~0x01;
	eax_100 = SEQ(eax_24_8_101, 0x00);
	goto l004017AA;
}

// 004017BA: void fn004017BA(Stack Eq_93 bArg04)
void fn004017BA(Eq_93 bArg04)
{
	if (fn00401DDA() != 0x00 && bArg04 == 0x00)
		globals->dw403358 = 0x00;
}

// 004017D7: void fn004017D7(Stack Eq_622 bArg08)
void fn004017D7(Eq_622 bArg08)
{
	if (globals->b40335C == 0x00 || bArg08 == 0x00)
	{
		fn004018F2();
		fn004018F2();
	}
}

// 00401841: Register ui32 fn00401841()
ui32 fn00401841()
{
	GetSystemTimeAsFileTime(fp - 0x10);
	ui32 v11_26 = dwLoc0C & 0x00 ^ dwLoc10 & 0x00 ^ GetCurrentThreadId() ^ GetCurrentProcessId();
	QueryPerformanceCounter(fp - 0x18);
	return dwLoc14 ^ dwLoc18 ^ v11_26 ^ fp - 0x08;
}

// 0040188E: void fn0040188E()
void fn0040188E()
{
	ui32 ecx_25 = globals->dw403004;
	if (ecx_25 == 0xBB40E64E || (ecx_25 & 0xFFFF0000) == 0x00)
	{
		ui32 eax_19 = fn00401841();
		ecx_25 = eax_19;
		if (eax_19 == 0xBB40E64E)
			ecx_25 = ~0x44BF19B0;
		else if ((eax_19 & 0xFFFF0000) == 0x00)
			ecx_25 = eax_19 | (eax_19 | 0x4711) << 0x10;
		globals->dw403004 = ecx_25;
	}
	globals->dw403000 = ~ecx_25;
}

// 004018F2: Register byte fn004018F2()
byte fn004018F2()
{
	return 0x01;
}

// 00401916: void fn00401916()
void fn00401916()
{
}

// 00401946: Register ptr32 fn00401946()
ptr32 fn00401946()
{
	return 0x004033AC;
}

// 0040194C: Register ptr32 fn0040194C()
ptr32 fn0040194C()
{
	return 0x004033A8;
}

// 00401952: void fn00401952(Stack word32 dwArg04)
void fn00401952(word32 dwArg04)
{
	if (IsProcessorFeaturePresent(0x17) == 0x00)
	{
		fn00401B16();
		memset(fp - 808, 0x00, 0x02CC);
		memset(fp - 0x5C, 0x00, 0x50);
		byte bl_90 = 0x00 - (IsDebuggerPresent() == 0x01);
		SetUnhandledExceptionFilter(null);
		if (UnhandledExceptionFilter(fp - 0x0C) == 0x00 && bl_90 == 0x01)
			fn00401B16();
	}
	else
		__fastfail(dwArg04);
}

// 00401A71: Register byte fn00401A71()
byte fn00401A71()
{
	Eq_990 eax_6 = GetModuleHandleW(null);
	if (eax_6 == null || eax_6->unused != 23117)
		return 0x00;
	struct Eq_1004 * ecx_15 = eax_6 + eax_6->dw003C / 0x0040;
	if (ecx_15->dw0000 != 0x4550 || (ecx_15->w0018 != 0x010B || (ecx_15->dw0074 <= 0x0E || ecx_15->dw00E8 == 0x00)))
		return 0x00;
	return 0x01;
}

// 00401B16: void fn00401B16()
void fn00401B16()
{
	globals->dw403388 &= 0x00;
}

// 00401B80: Register ptr32 fn00401B80(Register word32 ebx, Register Eq_93 esi, Register word32 edi, Stack word32 dwArg00, Stack ui32 dwArg08)
ptr32 fn00401B80(word32 ebx, Eq_93 esi, word32 edi, word32 dwArg00, ui32 dwArg08)
{
	ptr32 esp_14 = fp - 0x08 - dwArg08;
	*(esp_14 - 0x04) = ebx;
	*(esp_14 - 0x08) = (union Eq_93 *) esi;
	*(esp_14 - 0x0C) = edi;
	*(esp_14 - 0x0010) = globals->dw403004 ^ fp + 0x08;
	*(esp_14 - 0x0014) = dwArg00;
	fs->ptr0000 = fp - 0x08;
	return fp + 0x08;
}

// 00401C0A: void fn00401C0A(Register word32 edx, Register word32 ebx)
void fn00401C0A(word32 edx, word32 ebx)
{
	globals->dw40338C &= 0x00;
	globals->dw403010 |= 0x01;
	if (IsProcessorFeaturePresent(0x0A) != 0x00)
	{
		ui32 edi_135;
		__cpuid(0x00, 0x00, &0x00, &ebx, &0x00, &edx);
		__cpuid(0x01, 0x00, &0x01, &ebx, &0x00, &edx);
		if ((ebx ^ 1970169159 | 1818588270 | edx ^ 0x49656E69) == 0x00 && (0x00 == 0x000106C0 || (0x00 == 0x00020660 || (0x00 == 0x00020670 || (0x00 == 0x00030650 || (0x00 == 0x00030660 || false))))))
		{
			ui32 edi_92 = globals->dw403390;
			globals->dw403390 = edi_92 | 0x01;
			edi_135 = edi_92 | 0x01;
		}
		else
			edi_135 = globals->dw403390;
		Eq_1158 ebx_302;
		if (false)
		{
			__cpuid(0x07, 0x00, &0x07, &(fp - 0x28), &0x00, &edx);
			ebx_302 = fp - 0x28;
			if ((fp - 0x28 & 0x0200) != 0x00)
			{
				globals->dw403390 = edi_135 | 0x02;
				ebx_302 = fp - 0x28;
			}
		}
		else
			ebx_302 = dwLoc14 & 0x00;
		ui32 eax_141 = globals->dw403010;
		globals->dw40338C = 0x01;
		globals->dw403010 = eax_141 | 0x02;
		byte bl_179 = (byte) ebx_302;
		if (0x00 != 0x00)
		{
			globals->dw40338C = 0x02;
			globals->dw403010 = eax_141 | 0x02 | 0x04;
			if (0x00 != 0x00 && 0x00 != 0x00)
			{
				ui32 eax_160 = (word32) __xgetbv(0x00);
				if ((eax_160 & 0x06) == 0x06)
				{
					ui32 eax_175 = globals->dw403010;
					globals->dw40338C = 0x03;
					globals->dw403010 = eax_175 | 0x08;
					if ((bl_179 & 0x20) != 0x00)
					{
						globals->dw40338C = 0x05;
						globals->dw403010 = eax_175 | 0x08 | 0x20;
						if ((ebx_302 & 0xD0030000) == 0xD0030000 && (eax_160 & 0xE0) == 0xE0)
						{
							globals->dw403010 |= 0x40;
							globals->dw40338C = 0x06;
						}
					}
				}
			}
		}
	}
}

// 00401DDA: Register uint32 fn00401DDA()
uint32 fn00401DDA()
{
	return (uint32) (uint8) (globals->dw403014 != 0x00);
}

