// CheatMe.globals.c
// Generated by decompiling CheatMe.exe
// using Reko decompiler version 0.9.0.0.

#include "CheatMe.h"

word16 g_w400000 = 0x5A4D;
struct Eq_781 * g_ptr40003C = &g_t0100;
char g_str402110[] = "cls";
ui32 g_dw403000 = 0x44BF19B1;
ui32 g_dw403004 = 0xBB40E64E;
ui32 g_dw403010 = 0x00000001;
word32 g_dw403014 = 0x00000001;
Eq_68 g_t403018 = 
	{
		24
	};
byte g_b40301C = 0x3D;
byte g_b40301D = 0x3E;
uip32 g_dw403354 = 0x00000000;
word32 g_dw403358 = 0x00000000;
byte g_b40335C = 0x00;
ui32 g_dw403388 = 0x00000000;
ui32 g_dw40338C = 0x00000000;
ui32 g_dw403390 = 0x00000000;
struct Eq_54 * g_ptr403394 = null;
struct Eq_54 * g_ptr403398 = null;
Eq_781 g_t0100;

