//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x804a040

// ------------------------ Functions -------------------------

// Address range: 0x804852f - 0x804856f
int main(int argc, char ** argv) {
    // 0x804852f
    printf("Enter password: ");
    fflush((struct _IO_FILE *)g1);
    int32_t buf; // bp-80, 0x804852f
    return read(0, &buf, 100);
}

// --------------- Dynamically Linked Functions ---------------

// int fflush(FILE * stream);
// int printf(const char * restrict format, ...);
// ssize_t read(int fd, void * buf, size_t nbytes);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.4)
// Detected functions: 1
