In [1]:
# Task 1.1
def readFile(filename='RAINFALL.txt'):
    # Initialisation
    infile = open(filename, 'r')
    
    # Reading file
    data = []
    headerLine = next(infile)
    for line in infile:
        newRecord = line.strip().split(',')
        newRecord[1] = int(newRecord[1])
        data.append(newRecord)
    infile.close()
    
    return data

def totalRainy(data):
    totalRainPerYear = {}
    for record in data:
        year = record[0][:4] # First 4 characters
        days = record[1]
        if totalRainPerYear.get(year) == None:
            totalRainPerYear[year] = 0
        totalRainPerYear[year] += days
    return totalRainPerYear

def writeOut(totalRainPerYear, filename="RAINFALLYEAR.TXT"):
    outfile = open(filename, 'w') # Write mode
    outfile.write(f"Year,Rainy Days")
    for year in totalRainPerYear.keys():
        outfile.write(f"\n{year},{totalRainPerYear[year]}")
    outfile.close()
    
### Main ##############################
def task1_1():
    data = readFile()
    totalRainPerYear = totalRainy(data)
    writeOut(totalRainPerYear)
task1_1()

In [2]:
# Task 1.2
def ShowMenu(): # Procedure, just shows the menu text
    print('1. Query total rainy days in any year')
    print('2. Query by year the month of highest rainy days')
    print('3. -1 to exit')

In [10]:
# Task 1.3

def validateYear():
    year = input("Enter year: ").strip()
    while not (year.isdigit()): # year can be more than 4 digits?
        print("The year input is invalid")
        year = input("Enter year: ").strip()
    return year
    
def Query1():
    year = validateYear()
    ## Haha never say need read file you generated
    data = readFile('RAINFALLYEAR.txt')
    total = None
    for recordYear, count in data:
        if recordYear == year:
            total = count
    if total == None:
        print(f"The data for year {year} is not available")
    else:
        print(f"The total number of rainy days is {total}")
        
def Query2():
    # Initialisation
    givenYear = validateYear()
    data = readFile()
    
    # Month with max rainy days for the year
    maxMonth = ""
    maxDays = -1
    for record in data:
        year = record[0][:4]
        month = record[0][5:]
        days = record[1]
        if year == givenYear: # Must be of the specific year
            if maxDays < days:
                maxDays = days
                maxMonth = month
            elif maxDays == days:
                maxMonth += ',' + month
    if maxDays == -1:
        print(f"The data for year {givenYear} is not available")
    else:
        print(f"The month(s) with the highest number of rainy days of {maxDays} is {maxMonth}")
        
# Displays menu, asks them for their choice
def menu():
    run = True
    while run:
        ShowMenu()
        option = input("Enter option: ").strip()
        if option == "1":
            Query1()
        elif option == "2":
            Query2()
        elif option == "-1":
            run = False
        else:
            print("Invalid option")
        print()
menu()

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 1
Enter year: 1982
The total number of rainy days is 130

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 1
Enter year: 1999
The total number of rainy days is 177

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 1
Enter year: 19999
The data for year 19999 is not available

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 2
Enter year: 2018
The month(s) with the highest number of rainy days of 27 is 11

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: -1



## Task 1.4

Test Data
```
Input: Option:1, Year:19999
Purpose: Abnormal Data (Year not given)
Expected Output: The data for year 19999 is not available

Input: Option:1, Year:1982
Purpose: Normal Data, Test Querying the total nomber of rainy days in a year
Expected Output: The total number of rainy days is 130

Input: Option:2, Year:2018
Purpose: Extreme Data, Querying the largest/most recent year in the dataset
Expected Output: The month(s) with the highest number of rainy days of 27 is 11
```

In [8]:
# Task 1.4 (Continued)
menu()

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 1
Enter year: 19999
The data for year 19999 is not available

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 1
Enter year: 1982
The total number of rainy days is 130

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: 2
Enter year: 2018
The month(s) with the highest number of rainy days of 27 is 11

1. Query total rainy days in any year
2. Query by year the month of highest rainy days
3. -1 to exit
Enter option: -1

