//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_6f0(int32_t c);
int32_t function_700(char * s);
int32_t function_710(char * s);
void function_720(void);
int32_t function_730(char * format, ...);
int64_t * function_740(int32_t size);
int32_t function_750(char * format, ...);
int32_t function_760(void);
void function_770(int64_t * d);
int64_t locations(int128_t a1);
int64_t manual(void);
int64_t menu(void);
int64_t randomise(void);
int64_t register_tm_clones(void);
int64_t xor(int64_t str, int64_t str2);

// --------------------- Global Variables ---------------------

int64_t g1 = 2176; // 0x202d80
int64_t g2 = 2112; // 0x202d88
int64_t g3 = 0; // 0x203010
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x6c0 - 0x6d7
int64_t _init(void) {
    int64_t result = 0; // 0x6ce
    if (*(int64_t *)0x202fe8 != 0) {
        // 0x6d0
        __gmon_start__();
        result = &g4;
    }
    // 0x6d2
    return result;
}

// Address range: 0x6f0 - 0x6f6
int32_t function_6f0(int32_t c) {
    // 0x6f0
    return putchar(c);
}

// Address range: 0x700 - 0x706
int32_t function_700(char * s) {
    // 0x700
    return puts(s);
}

// Address range: 0x710 - 0x716
int32_t function_710(char * s) {
    // 0x710
    return strlen(s);
}

// Address range: 0x720 - 0x726
void function_720(void) {
    // 0x720
    __stack_chk_fail();
}

// Address range: 0x730 - 0x736
int32_t function_730(char * format, ...) {
    // 0x730
    return printf(format);
}

// Address range: 0x740 - 0x746
int64_t * function_740(int32_t size) {
    // 0x740
    return malloc(size);
}

// Address range: 0x750 - 0x756
int32_t function_750(char * format, ...) {
    // 0x750
    return scanf(format);
}

// Address range: 0x760 - 0x766
int32_t function_760(void) {
    // 0x760
    return rand();
}

// Address range: 0x770 - 0x776
void function_770(int64_t * d) {
    // 0x770
    __cxa_finalize(d);
}

// Address range: 0x780 - 0x7ab
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x780
    int64_t v1; // 0x780
    __libc_start_main(2186, (int32_t)a4, (char **)&v1, (void (*)())0x1110, (void (*)())0x1180, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x7b0 - 0x7e2
int64_t deregister_tm_clones(void) {
    // 0x7b0
    return &g3;
}

// Address range: 0x7f0 - 0x832
int64_t register_tm_clones(void) {
    // 0x7f0
    return 0;
}

// Address range: 0x840 - 0x87a
int64_t __do_global_dtors_aux(void) {
    // 0x840
    if (*(char *)&g3 != 0) {
        // 0x878
        int64_t result; // 0x840
        return result;
    }
    // 0x849
    if (*(int64_t *)0x202ff8 != 0) {
        // 0x857
        __cxa_finalize((int64_t *)*(int64_t *)0x203008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x863
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x880 - 0x88a
int64_t frame_dummy(void) {
    // 0x880
    return register_tm_clones();
}

// Address range: 0x88a - 0x89f
int main(int argc, char ** argv) {
    // 0x88a
    menu();
    return 0;
}

// Address range: 0x89f - 0x908
int64_t randomise(void) {
    int64_t v1 = __asm_movsd(__asm_cvtsi2sd(rand())); // 0x8b0
    int64_t v2 = __asm_movsd(__asm_cvtsi2sd(rand())); // 0x8be
    int128_t v3 = __asm_movapd(__asm_movsd_1(v2)); // 0x8cc
    printf("You are going to %lf, %lf...", (float64_t)(int64_t)__asm_movsd_1(v1), (float64_t)(int64_t)v3);
    __asm_movapd(__asm_movsd_1(v2));
    return locations(__asm_movsd_1(v1));
}

// Address range: 0x908 - 0x9b3
int64_t xor(int64_t str, int64_t str2) {
    int32_t len = strlen((char *)str); // 0x91f
    uint64_t len2 = (int64_t)strlen((char *)str2); // 0x934
    int64_t mem = (int64_t)malloc(len + 1); // 0x943
    int64_t v1 = 0; // 0x99d
    int32_t v2 = 0; // 0x99d
    if (len == 0) {
        // 0x99f
        *(char *)(mem + (int64_t)len) = 0;
        return mem;
    }
    char v3 = *(char *)(v1 + str); // 0x962
    char v4 = *(char *)(v1 % len2 + str2); // 0x97a
    *(char *)(v1 + mem) = v4 ^ v3;
    v2++;
    v1 = v2;
    while (v2 != len) {
        // 0x955
        v3 = *(char *)(v1 + str);
        v4 = *(char *)(v1 % len2 + str2);
        *(char *)(v1 + mem) = v4 ^ v3;
        v2++;
        v1 = v2;
    }
    // 0x99f
    *(char *)(mem + (int64_t)len) = 0;
    return mem;
}

// Address range: 0x9b3 - 0xb25
int64_t manual(void) {
    int64_t v1 = __readfsqword(40); // 0x9bb
    puts("Some of the popular spots in ShoppingBaba center: ");
    puts("Sample : Location @ X coordinate, Y coordinate");
    puts("1. CSIT Technology Centre @ 43434343, 67676767");
    puts("2. Kandell Food Court @ 23216789, 90942319 ");
    puts("3. Value101 @ 78783677, 67674343 ");
    puts("4. Cyberthon Information Centre @ 31313131, 75758989 ");
    puts("5. Chicken rice stall @ 71717171, 53535353 ");
    puts("6. Pokemon Center @ 21212121, 35455354");
    puts("7. Flag @ secret, secret ");
    putchar(10);
    int128_t v2; // 0x9b3
    int128_t v3 = __asm_pxor(v2, v2); // 0xa40
    int64_t v4 = __asm_movsd(v3); // bp-32, 0xa44
    int64_t v5 = __asm_movsd(__asm_pxor(v3, v3)); // bp-24, 0xa4d
    printf("Please enter the x to move around: ");
    int64_t v6; // 0x9b3
    if (scanf("%lf", &v4) != 0) {
        // 0xaa5
        printf("Please enter the y to move around: ");
        if (scanf("%lf", &v5) != 0) {
            // 0xaea
            putchar(10);
            __asm_movapd(__asm_movsd_1(v5));
            v6 = locations(__asm_movsd_1(v4));
        } else {
            // 0xad7
            puts("Enter a number please!");
            v6 = 0xffffffff;
        }
    } else {
        // 0xa92
        puts("Enter a number please!");
        v6 = 0xffffffff;
    }
    int64_t result = v6; // 0xb1c
    if (v1 != __readfsqword(40)) {
        // 0xb1e
        __stack_chk_fail();
        result = &g4;
    }
    // 0xb23
    return result;
}

// Address range: 0xb25 - 0xc52
int64_t menu(void) {
    int64_t v1 = __readfsqword(40); // 0xb2d
    puts("Welcome to ShoppingBaba's Annual Treasure Hunt game!");
    printf("Look for the flag hidden in this Treasure to win points!");
    puts("In this game, you can either navigate in ShoppingBaba center by the following ways:\n");
    puts("1: Move to a random spot");
    puts("2: Teleport to a known coordinate");
    puts("9: Exit the Treasure Hunt");
    putchar(10);
    int64_t v2 = -1; // bp-24, 0xb93
    printf("Please enter the option to move around: ");
    scanf("%d", &v2);
    int32_t v3 = v2; // 0xc33
    if (v3 != 9) {
        if (v3 != 1) {
            if (v3 == 2) {
                // 0xbe1
                if ((int32_t)manual() == -1) {
                    // break -> 0xc3b
                    break;
                }
            }
        } else {
            // 0xbcd
            randomise();
        }
        // 0xc0a
        printf("Please enter the option to move around: ");
        scanf("%d", &v2);
        int32_t v4 = v2; // 0xc33
        while (v4 != 9) {
            int32_t v5 = v4;
            if (v5 != 1) {
                if (v5 == 2) {
                    // 0xbe1
                    if ((int32_t)manual() == -1) {
                        // break -> 0xc3b
                        break;
                    }
                }
            } else {
                // 0xbcd
                randomise();
            }
            // 0xc0a
            printf("Please enter the option to move around: ");
            scanf("%d", &v2);
            v4 = v2;
        }
    }
    int64_t result = 0; // 0xc49
    if (v1 != __readfsqword(40)) {
        // 0xc4b
        __stack_chk_fail();
        result = &g4;
    }
    // 0xc50
    return result;
}

// Address range: 0xc52 - 0x110d
int64_t locations(int128_t a1) {
    // 0xc52
    int64_t v1; // bp-8, 0xc52
    int64_t v2 = (int64_t)&v1 - 48; // 0xc56
    unsigned char v3 = llvm_ctpop_i8((char)v2); // 0xc56
    int64_t v4 = __asm_movsd(a1); // 0xc5a
    int128_t v5; // 0xc52
    int64_t v6 = __asm_movsd(v5); // 0xc5f
    __asm_ucomisd(__asm_movsd_1(v4), 0x4184b60b38000000);
    int128_t v7 = __asm_movsd_1(v4);
    if (v3 % 2 == 0) {
        // 0xd2e
        __asm_ucomisd(v7, 0x4176242950000000);
    } else {
        // 0xc73
        __asm_ucomisd(v7, 0x4184b60b38000000);
        if (v2 == 0) {
            // 0xca0
            __asm_ucomisd(__asm_movsd_1(v6), 0x419022a97c000000);
            __asm_ucomisd(__asm_movsd_1(v6), 0x419022a97c000000);
            puts("You have landed at CSIT Technology Centre!");
            puts("Le random dude came to you and said: ");
            // 0x110a
            return puts("We conduct vulnerability assessments on critical software and infrastructure to find and assess security threats! \n");
        }
        // 0xcd8
        __asm_ucomisd(__asm_movsd_1(v4), 0x4176242950000000);
        __asm_ucomisd(__asm_movsd_1(v4), 0x4176242950000000);
    }
    // 0xd2e
    __asm_ucomisd(__asm_movsd_1(v4), 0x4192c892f4000000);
    int128_t v8 = __asm_movsd_1(v4);
    if (v3 % 2 == 0) {
        // 0xdf8
        __asm_ucomisd(v8, 0x417ddcceb0000000);
    } else {
        // 0xd3d
        __asm_ucomisd(v8, 0x4192c892f4000000);
        if (v2 == 0) {
            // 0xd6a
            __asm_ucomisd(__asm_movsd_1(v6), 0x419022839c000000);
            __asm_ucomisd(__asm_movsd_1(v6), 0x419022839c000000);
            puts("You have landed at Value101!");
            puts("There is something that looks like a flag!! ");
            // 0x110a
            return puts("It is just a popular Baba flag on display... \n");
        }
        // 0xda2
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddcceb0000000);
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddcceb0000000);
    }
    // 0xdf8
    __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
    __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
    if (v3 % 2 != 0) {
        if (v2 == 0) {
            // 0xe34
            __asm_ucomisd(__asm_movsd_1(v6), 0x41920ff610000000);
            __asm_ucomisd(__asm_movsd_1(v6), 0x41920ff610000000);
            puts("You have landed at somewhere!");
            puts("Le wild Pikachu appears and passes you a flag ");
            // 0x110a
            return puts("Le flag reads: you are really close but not close *troll face* with his signature 75753333 \n");
        }
        // 0xe70
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
    }
    // 0xef3
    __asm_ucomisd(__asm_movsd_1(v4), 0x4185aca688000000);
    int128_t v9 = __asm_movsd_1(v4);
    if (v3 % 2 == 0) {
        // 0xfc9
        __asm_ucomisd(v9, 0x417ddccec0000000);
    } else {
        // 0xf02
        __asm_ucomisd(v9, 0x4185aca688000000);
        if (v2 == 0) {
            // 0xf2f
            __asm_ucomisd(__asm_movsd_1(v6), 0x418e581608000000);
            __asm_ucomisd(__asm_movsd_1(v6), 0x418e581608000000);
            puts("You have landed at somewhere!");
            puts("Le wild chicken that escaped from the chicken rice appears ");
            puts("It appears to be holding on to a flag... ");
            // 0x110a
            return puts("He/she passes you the flag and it reads: *troll face* \n");
        }
        // 0xf73
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
        __asm_ucomisd(__asm_movsd_1(v4), 0x417ddccec0000000);
    }
    // 0xfc9
    __asm_ucomisd(__asm_movsd_1(v4), 0x41911944cc000000);
    int128_t v10 = __asm_movsd_1(v4);
    if (v3 % 2 == 0) {
        // 0x1090
        __asm_ucomisd(v10, 0x41743abd90000000);
    } else {
        // 0xfd8
        __asm_ucomisd(v10, 0x41911944cc000000);
        if (v2 == 0) {
            // 0x1005
            __asm_ucomisd(__asm_movsd_1(v6), 0x41898713c8000000);
            __asm_ucomisd(__asm_movsd_1(v6), 0x41898713c8000000);
            puts("You have landed at char * xor(char * message, char * key);the Chicken rice stall!");
            puts("They sell both white and roasted chickens! ");
            // 0x110a
            return puts("No signs of any flag though... \n");
        }
        // 0x103d
        __asm_ucomisd(__asm_movsd_1(v4), 0x41743abd90000000);
        __asm_ucomisd(__asm_movsd_1(v4), 0x41743abd90000000);
    }
    // 0x1090
    __asm_ucomisd(__asm_movsd_1(v4), 0x41653158e0000000);
    if (v3 % 2 == 0) {
        // 0x10f2
        puts("You have landed at some random spot!");
        // 0x110a
        return puts("There is nothing here... \n");
    }
    // 0x109f
    __asm_ucomisd(__asm_movsd_1(v4), 0x41653158e0000000);
    if (v2 != 0) {
        // 0x10f2
        puts("You have landed at some random spot!");
        // 0x110a
        return puts("There is nothing here... \n");
    }
    // 0x10cc
    __asm_ucomisd(__asm_movsd_1(v6), 0x41753158e0000000);
    __asm_ucomisd(__asm_movsd_1(v6), 0x41753158e0000000);
    puts("You have landed at a secret location!");
    puts("They are loads of flags in the chest! ");
    // 0x110a
    return puts("There are all Singapore flags though... \n");
}

// Address range: 0x1110 - 0x1175
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x113c
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1166
        return result;
    }
    int64_t v1 = 0; // 0x1144
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x1150
        v1++;
    }
    // 0x1166
    return result;
}

// Address range: 0x1180 - 0x1182
int64_t __libc_csu_fini(void) {
    // 0x1180
    int64_t result; // 0x1180
    return result;
}

// Address range: 0x1184 - 0x118d
int64_t _fini(void) {
    // 0x1184
    int64_t result; // 0x1184
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// void * malloc(size_t size);
// int printf(const char * restrict format, ...);
// int putchar(int c);
// int puts(const char * s);
// int rand(void);
// int scanf(const char * restrict format, ...);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.4.0)
// Detected functions: 24
