//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(void);
int32_t __x86_get_pc_thunk_bp(int32_t a1);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(int32_t a1, int32_t a2, int32_t a3);
int32_t _start(void);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1002(void);
int32_t function_1080(int32_t a1);
int32_t function_1082(void);
int32_t function_1090(int32_t a1, int32_t a2);
int32_t function_1092(void);
int32_t function_10a0(int32_t * a1);
int32_t function_10a2(void);
int32_t function_10b0(int32_t a1);
int32_t function_10b2(void);
int32_t function_10c0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_10c2(void);
int32_t function_10d2(void);
int32_t function_1106(int32_t a1, int32_t * a2, int32_t a3);
int32_t function_11b2(void);
int32_t function_1202(void);
int32_t function_120f(void);
int32_t function_12a2(int32_t a1);
int32_t function_1312(void);
int32_t function_131e(void);
int32_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int32_t _init(int32_t a1, int32_t a2, int32_t a3) {
    // 0x1000
    int32_t result; // 0x1000
    return result;
}

// Address range: 0x1002 - 0x1024
int32_t function_1002(void) {
    // 0x1002
    int16_t v1; // 0x1002
    __asm_sti(v1);
    int32_t v2; // 0x1002
    __x86_get_pc_thunk_bx(v2);
    return *(int32_t *)(v2 + 0x2fdf);
}

// Address range: 0x1080 - 0x1081
int32_t function_1080(int32_t a1) {
    // 0x1080
    int32_t result; // 0x1080
    return result;
}

// Address range: 0x1082 - 0x108a
int32_t function_1082(void) {
    // 0x1082
    int16_t v1; // 0x1082
    return __asm_sti(v1);
}

// Address range: 0x1090 - 0x1091
int32_t function_1090(int32_t a1, int32_t a2) {
    // 0x1090
    int32_t result; // 0x1090
    return result;
}

// Address range: 0x1092 - 0x109a
int32_t function_1092(void) {
    // 0x1092
    int16_t v1; // 0x1092
    return __asm_sti(v1);
}

// Address range: 0x10a0 - 0x10a1
int32_t function_10a0(int32_t * a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10a2 - 0x10aa
int32_t function_10a2(void) {
    // 0x10a2
    int16_t v1; // 0x10a2
    return __asm_sti(v1);
}

// Address range: 0x10b0 - 0x10b1
int32_t function_10b0(int32_t a1) {
    // 0x10b0
    int32_t result; // 0x10b0
    return result;
}

// Address range: 0x10b2 - 0x10ba
int32_t function_10b2(void) {
    // 0x10b2
    int16_t v1; // 0x10b2
    return __asm_sti(v1);
}

// Address range: 0x10c0 - 0x10c1
int32_t function_10c0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x10c0
    int32_t result; // 0x10c0
    return result;
}

// Address range: 0x10c2 - 0x10ca
int32_t function_10c2(void) {
    // 0x10c2
    int16_t v1; // 0x10c2
    return __asm_sti(v1);
}

// Address range: 0x10d0 - 0x10d1
int32_t _start(void) {
    // 0x10d0
    int32_t result; // 0x10d0
    return result;
}

// Address range: 0x10d2 - 0x1106
int32_t function_10d2(void) {
    // 0x10d2
    int16_t v1; // 0x10d2
    int32_t v2 = __asm_sti(v1); // 0x10d3
    int32_t v3 = v2; // bp-4, 0x10dc
    int32_t v4; // 0x10d2
    function_1106(v4, &v3, v2);
    int32_t v5; // 0x10d2
    int32_t v6 = *(int32_t *)(v5 + 0x2f14); // 0x10fa
    int32_t v7; // 0x10d2
    function_10c0(v6, (int32_t)v1, &v7, v5 + 444, v5 + 556);
    return __asm_hlt();
}

// Address range: 0x1106 - 0x110a
int32_t function_1106(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x1106
    int32_t result; // 0x1106
    return result;
}

// Address range: 0x1110 - 0x1114
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x1110
    int32_t result; // 0x1110
    return result;
}

// Address range: 0x1120 - 0x1159
int32_t deregister_tm_clones(void) {
    // 0x1120
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x1120
    return v1 + 0x2ee3;
}

// Address range: 0x1160 - 0x11a7
int32_t register_tm_clones(void) {
    // 0x1160
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x11b0 - 0x11b1
int32_t __do_global_dtors_aux(void) {
    // 0x11b0
    int32_t result; // 0x11b0
    return result;
}

// Address range: 0x11b2 - 0x11fb
int32_t function_11b2(void) {
    // 0x11b2
    int16_t v1; // 0x11b2
    __asm_sti(v1);
    int32_t v2; // 0x11b2
    int32_t result = __x86_get_pc_thunk_bx(v2); // 0x11b8
    char * v3 = (char *)(v2 + 0x2e4b); // 0x11c6
    if (*v3 != 0) {
        // 0x11f6
        return result;
    }
    // 0x11cf
    if (*(int32_t *)(v2 + 0x2e2b) != 0) {
        // 0x11d9
        function_1080(*(int32_t *)(v2 + 0x2e47));
    }
    int32_t result2 = deregister_tm_clones(); // 0x11ea
    *v3 = 1;
    // 0x11f6
    return result2;
}

// Address range: 0x1200 - 0x1201
int32_t frame_dummy(void) {
    // 0x1200
    int32_t result; // 0x1200
    return result;
}

// Address range: 0x1202 - 0x1209
int32_t function_1202(void) {
    // 0x1202
    int16_t v1; // 0x1202
    __asm_sti(v1);
    return register_tm_clones();
}

// Address range: 0x1209 - 0x120d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1209
    int32_t result; // 0x1209
    return result;
}

// Address range: 0x120d - 0x120e
int main(int argc, char ** argv) {
    // 0x120d
    int32_t result; // 0x120d
    return result;
}

// Address range: 0x120f - 0x1297
int32_t function_120f(void) {
    // 0x120f
    int16_t v1; // 0x120f
    __asm_sti(v1);
    int32_t v2; // 0x120f
    __x86_get_pc_thunk_bx(v2);
    function_1090(*(int32_t *)*(int32_t *)(v2 + 0x2dd0), 0);
    function_1090(*(int32_t *)*(int32_t *)(v2 + 0x2dd4), 0);
    function_1090(*(int32_t *)*(int32_t *)(v2 + 0x2dc4), 0);
    int32_t v3; // bp-270, 0x120f
    function_10a0(&v3);
    return 0;
}

// Address range: 0x12a0 - 0x12a1
int32_t __libc_csu_init(void) {
    // 0x12a0
    int32_t result; // 0x12a0
    return result;
}

// Address range: 0x12a2 - 0x1305
int32_t function_12a2(int32_t a1) {
    // 0x12fd
    int16_t v1; // 0x12a2
    __asm_sti(v1);
    int32_t v2; // 0x12a2
    __x86_get_pc_thunk_bp(v2);
    int32_t v3; // bp-30, 0x12a2
    int32_t v4 = &v3; // 0x12b3
    int32_t v5; // 0x12a2
    int32_t v6; // 0x12a2
    int32_t v7; // 0x12a2
    _init(v7, v6, v5);
    *(int32_t *)(v4 - 8) = a1;
    *(int32_t *)(v4 - 12) = *(int32_t *)(v4 + 36);
    *(int32_t *)(v4 - 16) = *(int32_t *)(v4 + 32);
    return v2 + 0x2c1a;
}

// Address range: 0x1310 - 0x1311
int32_t __libc_csu_fini(void) {
    // 0x1310
    int32_t result; // 0x1310
    return result;
}

// Address range: 0x1312 - 0x1315
int32_t function_1312(void) {
    // 0x1312
    int16_t v1; // 0x1312
    return __asm_sti(v1);
}

// Address range: 0x1315 - 0x1319
int32_t __x86_get_pc_thunk_bp(int32_t a1) {
    // 0x1315
    int32_t result; // 0x1315
    return result;
}

// Address range: 0x131c - 0x131d
int32_t _fini(void) {
    // 0x131c
    int32_t result; // 0x131c
    return result;
}

// Address range: 0x131e - 0x1334
int32_t function_131e(void) {
    // 0x131e
    int16_t v1; // 0x131e
    __asm_sti(v1);
    int32_t v2; // 0x131e
    return __x86_get_pc_thunk_bx(v2);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 32
