//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
char * function_620(char * dest, char * src);
int32_t function_630(char * s);
int32_t function_640(char * s);
void function_650(void);
int32_t function_660(char * format, ...);
void function_670(int64_t * d);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 1920; // 0x200d98
int64_t g2 = 1856; // 0x200da0
int64_t g3 = 0; // 0x201010
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x5f0 - 0x607
int64_t _init(void) {
    int64_t result = 0; // 0x5fe
    if (*(int64_t *)0x200fe8 != 0) {
        // 0x600
        __gmon_start__();
        result = &g4;
    }
    // 0x602
    return result;
}

// Address range: 0x620 - 0x626
char * function_620(char * dest, char * src) {
    // 0x620
    return strcpy(dest, src);
}

// Address range: 0x630 - 0x636
int32_t function_630(char * s) {
    // 0x630
    return puts(s);
}

// Address range: 0x640 - 0x646
int32_t function_640(char * s) {
    // 0x640
    return strlen(s);
}

// Address range: 0x650 - 0x656
void function_650(void) {
    // 0x650
    __stack_chk_fail();
}

// Address range: 0x660 - 0x666
int32_t function_660(char * format, ...) {
    // 0x660
    return printf(format);
}

// Address range: 0x670 - 0x676
void function_670(int64_t * d) {
    // 0x670
    __cxa_finalize(d);
}

// Address range: 0x680 - 0x6ab
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x680
    int64_t v1; // 0x680
    __libc_start_main(1930, (int32_t)a4, (char **)&v1, (void (*)())2352, (void (*)())2464, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x6b0 - 0x6e2
int64_t deregister_tm_clones(void) {
    // 0x6b0
    return &g3;
}

// Address range: 0x6f0 - 0x732
int64_t register_tm_clones(void) {
    // 0x6f0
    return 0;
}

// Address range: 0x740 - 0x77a
int64_t __do_global_dtors_aux(void) {
    // 0x740
    if (*(char *)&g3 != 0) {
        // 0x778
        int64_t result; // 0x740
        return result;
    }
    // 0x749
    if (*(int64_t *)0x200ff8 != 0) {
        // 0x757
        __cxa_finalize((int64_t *)*(int64_t *)0x201008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x763
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x780 - 0x78a
int64_t frame_dummy(void) {
    // 0x780
    return register_tm_clones();
}

// Address range: 0x78a - 0x929
int main(int argc, char ** argv) {
    int32_t v1 = argc; // 0x796
    int64_t v2 = __readfsqword(40); // 0x7a3
    int64_t v3; // 0x78a
    if (v1 > 1) {
        if (v1 == 2) {
            int64_t * str = (int64_t *)((int64_t)argv + 8); // 0x7fb
            if (strlen((char *)*str) == 33) {
                // 0x82b
                int64_t str2; // bp-120, 0x78a
                strcpy((char *)&str2, (char *)*str);
                int64_t str3 = 0x1486a6a24761e04; // bp-72, 0x85c
                int32_t len = strlen((char *)&str3); // 0x8e1
                int32_t v4 = 0; // 0x8e9 //--------------------------------------------------------------------Index of array
                if (len != 0) {
                    int64_t v5; // bp-8, 0x78a //----------------------------------------------------------------memory location
                    int64_t v6 = (int64_t)v4 + (int64_t)&v5; //---------------------------------v6 = v5+v4 = &v5[v4]
                    char v7 = *(char *)(v6 - 112); // 0x8a7 ----------------------------------------v7 = v5[v4-112] = str2[v4]
                    *(char *)(v6 - 160) = v7 ^ *(char *)(v6 - 64); // --------------------------------v6-160 = bp-168 + v4 = v9[v4] = str2[v4] ^ str3[v4]
                    int32_t v8 = v4 + 1; // 0x8ca
                    uint32_t len2 = strlen((char *)&str3); // 0x8e1 //------------------------strlen(str3)
                    v4 = v8; //---------------------------------------------------------------- v4+=1
                    while (v8 < len2) {
                        // 0x892
                        v6 = (int64_t)v4 + (int64_t)&v5;
                        v7 = *(char *)(v6 - 112);
                        *(char *)(v6 - 160) = v7 ^ *(char *)(v6 - 64);
                        v8 = v4 + 1;
                        len2 = strlen((char *)&str3);
                        v4 = v8; //-------------------------------------------------------------- v4+=1
                    }
                }
                // 0x8eb
                int64_t v9; // bp-168, 0x78a
                printf("Your flag is: %s\n", &v9);
                v3 = 0;
            } else {
                // 0x815
                puts("33 is the magic number! ;)");
                v3 = 1;
            }
        } else {
            // 0x7da
            puts("I am overwhelmed! @.@");
            v3 = 1;
        }
    } else {
        // 0x7bb
        puts("Insufficient arguments. Gimme moarrrrrr");
        v3 = 1;
    }
    int64_t result = v3; // 0x918
    if (v2 != __readfsqword(40)) {
        // 0x91a
        __stack_chk_fail();
        result = &g4;
    }
    // 0x91f
    return result;
}

// Address range: 0x930 - 0x995
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x95c
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x986
        return result;
    }
    int64_t v1 = 0; // 0x964
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x970
        v1++;
    }
    // 0x986
    return result;
}

// Address range: 0x9a0 - 0x9a2
int64_t __libc_csu_fini(void) {
    // 0x9a0
    int64_t result; // 0x9a0
    return result;
}

// Address range: 0x9a4 - 0x9ad
int64_t _fini(void) {
    // 0x9a4
    int64_t result; // 0x9a4
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// char * strcpy(char * restrict dest, const char * restrict src);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 16
