//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t _start(void);

// ------------------------ Functions -------------------------

// Address range: 0x8048060 - 0x804809d
int32_t _start(void) {
    // 0x8048060
    __asm_int(128);
    __asm_int(128);
    return 3;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.x)
// Detected functions: 1
