//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(int32_t a1);
int32_t __stack_chk_fail_local(void);
int32_t __x86_get_pc_thunk_ax(int32_t result, int32_t a2, int32_t a3, int32_t a4);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t check(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_460(int32_t a1);
int32_t function_470(void);
int32_t function_480(int32_t * a1);
int32_t function_490(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_4a0(int32_t a1, int32_t * a2);
int32_t function_4b0(int32_t a1);
int32_t function_4b8(void);
int32_t function_4f2(int32_t a1, int32_t * a2, int32_t a3);
int32_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 1; // 0x170
int32_t g2;

// ------------------------ Functions -------------------------

// Address range: 0x420 - 0x443
int32_t _init(void) {
    // 0x420
    int32_t v1; // 0x420
    __x86_get_pc_thunk_bx(v1);
    int32_t result = 0; // 0x437
    if (*(int32_t *)(v1 + 0x1bcb) != 0) {
        // 0x439
        result = function_4b8();
    }
    // 0x43e
    return result;
}

// Address range: 0x460 - 0x466
int32_t function_460(int32_t a1) {
    // 0x460
    int32_t result; // 0x460
    return result;
}

// Address range: 0x470 - 0x476
int32_t function_470(void) {
    // 0x470
    int32_t result; // 0x470
    return result;
}

// Address range: 0x480 - 0x486
int32_t function_480(int32_t * a1) {
    // 0x480
    int32_t result; // 0x480
    return result;
}

// Address range: 0x490 - 0x496
int32_t function_490(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x490
    int32_t result; // 0x490
    return result;
}

// Address range: 0x4a0 - 0x4a6
int32_t function_4a0(int32_t a1, int32_t * a2) {
    // 0x4a0
    int32_t result; // 0x4a0
    return result;
}

// Address range: 0x4b0 - 0x4b6
int32_t function_4b0(int32_t a1) {
    // 0x4b0
    int32_t result; // 0x4b0
    return result;
}

// Address range: 0x4b8 - 0x4be
int32_t function_4b8(void) {
    // 0x4b8
    int32_t result; // 0x4b8
    return result;
}

// Address range: 0x4c0 - 0x4f2
int32_t _start(int32_t a1) {
    // 0x4c0
    int32_t v1; // bp-4, 0x4c0
    int32_t v2; // 0x4c0
    int32_t v3; // 0x4c0
    function_4f2(v2, &v1, v3);
    int32_t v4; // 0x4c0
    int32_t v5; // 0x4c0
    function_490(*(int32_t *)(v5 + 0x1b28), a1, &v4, v5 + 800, v5 + 896);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x4f2 - 0x4f6
int32_t function_4f2(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x4f2
    int32_t result; // 0x4f2
    return result;
}

// Address range: 0x500 - 0x504
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x500
    int32_t result; // 0x500
    return result;
}

// Address range: 0x510 - 0x54a
int32_t deregister_tm_clones(void) {
    // 0x510
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x510
    return v1 + 0x1af3;
}

// Address range: 0x550 - 0x597
int32_t register_tm_clones(void) {
    // 0x550
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x5a0 - 0x5e7
int32_t __do_global_dtors_aux(void) {
    // 0x5a0
    int32_t v1; // 0x5a0
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x5a4
    char * v2 = (char *)(v1 + 0x1a5f); // 0x5b2
    if (*v2 != 0) {
        // 0x5e2
        return result;
    }
    // 0x5bb
    if (*(int32_t *)(v1 + 0x1a47) != 0) {
        // 0x5c5
        function_4b0(*(int32_t *)(v1 + 0x1a5b));
    }
    int32_t result2 = deregister_tm_clones(); // 0x5d6
    *v2 = 1;
    // 0x5e2
    return result2;
}

// Address range: 0x5f0 - 0x5f9
int32_t frame_dummy(void) {
    // 0x5f0
    return register_tm_clones();
}

// Address range: 0x5f9 - 0x5fd
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x5f9
    int32_t result; // 0x5f9
    return result;
}

// Address range: 0x5fd - 0x6f6
int32_t check(int32_t a1) {
    // 0x5fd
    int32_t v1; // 0x5fd
    int32_t v2; // 0x5fd
    int32_t v3; // 0x5fd
    int32_t v4; // 0x5fd
    __x86_get_pc_thunk_ax(v4, v2, v1, v3);
    int32_t v5 = __readgsdword(20); // 0x613
    int32_t v6 = 0x43444443; // bp-55, 0x622
    if (a1 == -0xff23502) {
        for (int32_t i = 0; i < 14; i++) {
            // 0x69d
            int32_t v7; // bp-4, 0x5fd
            char * v8 = (char *)((int32_t)&v7 - 44 + i); // 0x6a4
            *v8 = *v8 ^ (char)i;
        }
        // 0x6ca
        function_480(&v6);
    }
    int32_t result = 0; // 0x6e7
    if (v5 != __readgsdword(20)) {
        // 0x6e9
        result = __stack_chk_fail_local();
    }
    // 0x6ee
    return result;
}

// Address range: 0x6f6 - 0x7df
int main(int argc, char ** argv) {
    // 0x6f6
    int32_t v1; // 0x6f6
    __x86_get_pc_thunk_bx((int32_t)&v1);
    int32_t v2 = __readgsdword(20); // 0x713
    int32_t v3 = 0; // bp-24, 0x71e
    int32_t v4; // 0x6f6
    function_480((int32_t *)(v4 + 387));
    function_480((int32_t *)(v4 + 451));
    function_480((int32_t *)(v4 + 515));
    function_480((int32_t *)(v4 + 579));
    function_460(v4 + 643);
    function_4a0(v4 + 677, &v3);
    check(v3);
    int32_t result = 0; // 0x7ce
    if (v2 != __readgsdword(20)) {
        // 0x7d0
        result = __stack_chk_fail_local();
    }
    // 0x7d5
    return result;
}

// Address range: 0x7df - 0x7e3
int32_t __x86_get_pc_thunk_ax(int32_t result, int32_t a2, int32_t a3, int32_t a4) {
    // 0x7df
    return result;
}

// Address range: 0x7f0 - 0x84d
int32_t __libc_csu_init(int32_t a1) {
    // 0x845
    int32_t v1; // 0x7f0
    __x86_get_pc_thunk_bx(v1);
    int32_t v2; // bp-28, 0x7f0
    int32_t v3 = &v2; // 0x7ff
    _init();
    *(int32_t *)(v3 - 8) = a1;
    *(int32_t *)(v3 - 12) = *(int32_t *)(v3 + 36);
    *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 32);
    return v1 + 0x16d3;
}

// Address range: 0x850 - 0x852
int32_t __libc_csu_fini(void) {
    // 0x850
    int32_t result; // 0x850
    return result;
}

// Address range: 0x860 - 0x874
int32_t __stack_chk_fail_local(void) {
    // 0x860
    int32_t v1; // 0x860
    __x86_get_pc_thunk_bx(v1);
    return function_470();
}

// Address range: 0x874 - 0x888
int32_t _fini(void) {
    // 0x874
    int32_t v1; // 0x874
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 23
