/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void free(void *ptr);
// int puts(const char *s);
// size_t strcspn(const char *s, const char *reject);
// char *fgets(char *s, int n, FILE *stream);
// int strcmp(const char *s1, const char *s2);
// FILE *fopen(const char *filename, const char *modes);
unsigned __int64 __fastcall main(__int64 a1, char **a2, char **a3);
__int64 __fastcall sub_15A0(_QWORD); // weak
__int64 __fastcall sub_1620(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall sub_1640(char *s1); // idb

//-------------------------------------------------------------------------
// Data declarations

__int64 qword_100 = 4096LL; // weak
FILE *stdin; // idb


//----- (00000000000010B0) ----------------------------------------------------
unsigned __int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  char v3; // r14
  char v4; // r13
  int v5; // er12
  char *v6; // rbp
  int v7; // er15
  signed __int64 v8; // rdi
  char *v9; // rbp
  char *v10; // rbp
  char *v11; // rsi
  __int64 v12; // rdx
  char *v13; // rbp
  int v14; // er15
  char *v15; // rbp
  int v16; // er15
  char *v17; // rbp
  int v18; // er15
  int v19; // er15
  __int64 v20; // rdx
  char *v21; // rbp
  int v22; // er15
  int v23; // er15
  __int64 v24; // rdx
  char *v25; // rsi
  int v26; // er15
  __int64 v27; // rdx
  char *v28; // r12
  char *v29; // rsi
  FILE *v30; // r13
  __int64 v31; // rdx
  __int64 v32; // rdx
  unsigned __int64 result; // rax
  unsigned __int64 v34; // rt1
  char v35; // al
  __int64 v36; // rdx
  __int64 v37; // rdx
  char v38[256]; // [rsp+0h] [rbp-248h]
  char s[264]; // [rsp+100h] [rbp-148h]
  unsigned __int64 v40; // [rsp+208h] [rbp-40h]

  v3 = 0;
  v4 = 1;
  v5 = 0;
  v40 = __readfsqword(0x28u);
  sub_1620(1LL, a2, a3);
  while ( 1 )
  {
    v10 = (char *)sub_15A0(0LL);
    puts(v10);
    free(v10);
    v11 = (char *)&qword_100;
    if ( !fgets(v38, 256, stdin) )
      goto LABEL_24;
    v38[strcspn(v38, "\n")] = 0;
    if ( v5 )
      break;
    v6 = (char *)sub_15A0(2LL);
    v7 = strcmp(v38, v6);
    free(v6);
    if ( v7 )
    {
      v11 = (char *)sub_15A0(6LL);
      v19 = strcmp(v38, v11);
      free(v11);
      if ( !v19 )
      {
        sub_1620(7LL, v11, v20);
LABEL_24:
        sub_1620(5LL, v11, v12);
        goto LABEL_25;
      }
      v21 = (char *)sub_15A0(9LL);
      v22 = strcmp(v38, v21);
      free(v21);
      v8 = 10LL;
      if ( !v22 )
        goto LABEL_5;
      v11 = (char *)sub_15A0(11LL);
      v23 = strcmp(v38, v11);
      free(v11);
      if ( v23 )
      {
        v35 = sub_1640(v38);
        if ( v35 )
        {
          if ( v3 )
          {
            if ( !(unsigned __int8)sub_1640(v38) )
              goto LABEL_30;
LABEL_33:
            v3 = 1;
            v4 = 0;
            sub_1620(17LL, 14LL, v37);
          }
          else
          {
            v3 = v35;
            sub_1620(16LL, 15LL, v36);
          }
        }
        else
        {
          if ( (unsigned __int8)sub_1640(v38) && v3 )
            goto LABEL_33;
LABEL_30:
          sub_1620(4LL, 14LL, v37);
        }
      }
      else
      {
        if ( v4 )
        {
          sub_1620(12LL, v11, v24);
          goto LABEL_24;
        }
        v5 = 1;
        sub_1620(13LL, v11, v24);
      }
    }
    else
    {
      v8 = 3LL;
      if ( !v4 )
        v8 = 8LL;
LABEL_5:
      v9 = (char *)sub_15A0(v8);
      puts(v9);
      free(v9);
    }
  }
  v13 = (char *)sub_15A0(2LL);
  v14 = strcmp(v38, v13);
  free(v13);
  v8 = 18LL;
  if ( !v14 )
    goto LABEL_5;
  if ( v5 != 1337 || (v25 = (char *)sub_15A0(23LL), v26 = strcmp(v38, v25), free(v25), v26) )
  {
    v15 = (char *)sub_15A0(19LL);
    v16 = strcmp(v38, v15);
    free(v15);
    if ( v16 )
    {
      v17 = (char *)sub_15A0(20LL);
      v18 = strcmp(v38, v17);
      free(v17);
      v8 = 4LL;
      if ( !v18 )
      {
        v5 = 2 * v5 + 1;
        v8 = 22LL;
      }
    }
    else
    {
      v5 *= 2;
      v8 = 21LL;
    }
    goto LABEL_5;
  }
  sub_1620(24LL, v25, v27);
  v28 = (char *)sub_15A0(25LL);
  v29 = (char *)sub_15A0(26LL);
  v30 = fopen(v28, v29);
  free(v28);
  free(v29);
  if ( v30 )
  {
    fgets(s, 256, v30);
    v29 = "\n";
    s[strcspn(s, "\n")] = 0;
    puts(s);
  }
  else
  {
    sub_1620(27LL, v29, v31);
  }
  sub_1620(28LL, v29, v32);
LABEL_25:
  v34 = __readfsqword(0x28u);
  result = v40 - v34;
  if ( v40 == v34 )
    result = 0LL;
  return result;
}
// 100: using guessed type __int64 qword_100;
// 15A0: using guessed type __int64 __fastcall sub_15A0(_QWORD);
// 1620: using guessed type __int64 __fastcall sub_1620(_QWORD, _QWORD, _QWORD);
// 10B0: using guessed type char var_248[256];
// 10B0: using guessed type char s[264];

// ALL OK, 1 function(s) have been successfully decompiled
