SELECT SaleDate, SalesPersonName, CustomerName FROM 
(SALE INNER JOIN CUSTOMER ON SALE.CustomerID == CUSTOMER.CustomerID
INNER JOIN SALESPERSON ON SALE.SalesPersonID == SALESPERSON.SalesPersonID
INNER JOIN OFFICE ON SALESPERSON.OfficeID == OFFICE.OfficeID)
WHERE OFFICE.OfficeID == 1;
