//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------------ Functions -------------------------

// Address range: 0x8049216 - 0x8049217
int main(int argc, char ** argv) {
    // 0x8049216
    int32_t result; // 0x8049216
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (10.3.0)
// Detected functions: 1
